### ISSUE TITLE
genabi: handle json file with 0 events

### ISSUE THREAD

**Issue by ryandotsmith** [indexsupply/x#89]
Currently a no-event json file produces an invalid go file

**Comment by worm-emoji** [comment]
is this resolved in https://github.com/indexsupply/x/commit/5dc7b49bfd5230bb84f38be15cadd615bb211e46 ?

**Comment by ryandotsmith** [comment]
Fixed in 1bedb67259f8631dc0db94527db5b55fdb9d2a84
